/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleForm: typeof import('./src/components/ArticleForm.vue')['default']
    ArticleItem: typeof import('./src/components/ArticleItem.vue')['default']
    ArticleList: typeof import('./src/components/ArticleList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
  }
}
